export const APP = {
    INITIALIZE_UPSELL_ADDING: 'APP@INITIALIZE_UPSELL_ADDING',
    BUY_UPSELL: 'APP@BUY_UPSELL',
    ADD_UPSELL: 'APP@ADD_UPSELL',
    STOP_BUYING_UPSELL: 'APP@STOP_BUYING_UPSELL',
    CHANGE_POPUP_VISIBILITY: 'APP@CHANGE_POPUP_VISIBILITY',
};
